// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Warehouse_EF_WinForms_App.Contexts;

#nullable disable

namespace WarehouseEFWinFormsApp.Migrations
{
    [DbContext(typeof(WarehouseContext))]
    [Migration("20230211051547_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Warehouse_EF_WinForms_App.Entities.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GoodsId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Deliveri__3214EC075FADAC59");

                    b.HasIndex(new[] { "GoodsId" }, "IX_Deliveries_GoodsId");

                    b.HasIndex(new[] { "SupplierId" }, "IX_Deliveries_SupplierId");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("Warehouse_EF_WinForms_App.Entities.Good", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("money");

                    b.Property<int>("GoodsTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Goods__3214EC07A3278453");

                    b.HasIndex(new[] { "GoodsTypeId" }, "IX_Goods_GoodsTypeId");

                    b.ToTable("Goods");
                });

            modelBuilder.Entity("Warehouse_EF_WinForms_App.Entities.GoodsType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__GoodsTyp__3214EC07D588955F");

                    b.ToTable("GoodsTypes");
                });

            modelBuilder.Entity("Warehouse_EF_WinForms_App.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Supplier__3214EC079DF34C90");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Warehouse_EF_WinForms_App.Entities.Delivery", b =>
                {
                    b.HasOne("Warehouse_EF_WinForms_App.Entities.Good", "Goods")
                        .WithMany("Deliveries")
                        .HasForeignKey("GoodsId")
                        .IsRequired()
                        .HasConstraintName("FK__Deliverie__Goods__2B3F6F97");

                    b.HasOne("Warehouse_EF_WinForms_App.Entities.Supplier", "Supplier")
                        .WithMany("Deliveries")
                        .HasForeignKey("SupplierId")
                        .IsRequired()
                        .HasConstraintName("FK__Deliverie__Suppl__2C3393D0");

                    b.Navigation("Goods");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Warehouse_EF_WinForms_App.Entities.Good", b =>
                {
                    b.HasOne("Warehouse_EF_WinForms_App.Entities.GoodsType", "GoodsType")
                        .WithMany("Goods")
                        .HasForeignKey("GoodsTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Goods__GoodsType__286302EC");

                    b.Navigation("GoodsType");
                });

            modelBuilder.Entity("Warehouse_EF_WinForms_App.Entities.Good", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("Warehouse_EF_WinForms_App.Entities.GoodsType", b =>
                {
                    b.Navigation("Goods");
                });

            modelBuilder.Entity("Warehouse_EF_WinForms_App.Entities.Supplier", b =>
                {
                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
